// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqi9aNuhAE9ppshBtiYI1htbF-nk3FWrU',
    appId: '1:522159891901:web:92e0f9943e6abce1dc1ed4',
    messagingSenderId: '522159891901',
    projectId: 'taskvine',
    authDomain: 'taskvine.firebaseapp.com',
    storageBucket: 'taskvine.appspot.com',
    measurementId: 'G-B3L644H7ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLw1DoaCzlmGrNi-CCOIs9415zhkxCeyQ',
    appId: '1:522159891901:android:39a7a7f68f946d19dc1ed4',
    messagingSenderId: '522159891901',
    projectId: 'taskvine',
    storageBucket: 'taskvine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRplr6uMY4SAYsKW5XacLANdiJOYAqSVo',
    appId: '1:522159891901:ios:ee2c395e5c8b8607dc1ed4',
    messagingSenderId: '522159891901',
    projectId: 'taskvine',
    storageBucket: 'taskvine.appspot.com',
    iosBundleId: 'com.appventure.taskvine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRplr6uMY4SAYsKW5XacLANdiJOYAqSVo',
    appId: '1:522159891901:ios:ee2c395e5c8b8607dc1ed4',
    messagingSenderId: '522159891901',
    projectId: 'taskvine',
    storageBucket: 'taskvine.appspot.com',
    iosBundleId: 'com.appventure.taskvine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqi9aNuhAE9ppshBtiYI1htbF-nk3FWrU',
    appId: '1:522159891901:web:e4895e5633dd1bebdc1ed4',
    messagingSenderId: '522159891901',
    projectId: 'taskvine',
    authDomain: 'taskvine.firebaseapp.com',
    storageBucket: 'taskvine.appspot.com',
    measurementId: 'G-8201Y7TFXH',
  );
}
